config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root("pages#home")
  get("about", to: "pages#about")
  get("contact", to: "pages#contact")
  mount Ckeditor::Engine => '/ckeditor'
  resources :articles

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true,length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum:10, maximum: 300 }

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/assets.rb
class Ckeditor::Assets < ActiveRecord::Base
include Ckeditor::Orm::ActiveRecord::AssetsBase

delegate :url, :current_path, :content_type, to: :data

validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit] #can do this if there is a repeative call

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def edit

  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:success] = "Article was successfully created" #:success gives a green background to the message
      redirect_to article_path(@article)
    else
      render 'new'
    end
    end

  def create
    #render plain: params[:article].inspect
    @article = Article.new(article_params)
    # @article.save

    if @article.save
    flash[:success] = "Article was successfully created"
    redirect_to article_path(@article)
    else
    render 'new'

    end
  end
  def show
    @article = Article.find(params[:id])
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash[:danger]= "Article was successfully deleted" #:danger gives a red background to the delete message
    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :description)
    end

    def set_article
      @article = Article.find(params[:id])
    end

  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home

  end

  def about

  end

  def contact

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%=render 'shared/errors', obj: @article%>

<div class = 'row'>
  <div class='col-xs-12'>

    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>

        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :title %><br>
          </div>

          <div class="col-sm-8">
            <%= f.text_field :title, class: "form-control", placeholder: 'Title of Article' , autofocus:true %>
          </div>
        </div>


        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :description %><br>
          </div>

          <div class="col-sm-8">

            <%= f.cktext_area :description%>
          </div>




        <div class="form-group">
          <div class=" col-sm-10 col-xs-offset-5" style=" padding-top: 10px">
          <%= f.submit class: 'btn btn-primary btn-lg' %>
          </div>
        </div>



<% end %>

    <div class="col-xs-4 col-xs-offset-4" style="padding-left: 40px">
     [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
    </div>
  </div>

</div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Edit Existing Article</h1>

<% if @article.errors.any? %>
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
      <% end %>
    </ul>
<% end %>

<%= render "form" %>

app/views/articles/index.html.erb
<h1 align="center">Listing All Articles</h1>
<div class="col-xs-8 col-xs-offset-2" style="padding-bottom: 5px"><%= link_to "Create new article", new_article_path, class: "btn btn-xs btn-primary" %></div>


  <% @articles.each do |article| %>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="well well-lg">
          <div class="article-title">
            <%= link_to article.title, article_path(article)%>
          </div>
          <div class="article-body">
            <%= truncate(article.description.html_safe, length:100, :escape => false)  %>
          </div>

        <div class="article-actions">

          <%= link_to "Edit Article", edit_article_path(article), class: "btn btn-xs btn-success  float1" %>

          <%= link_to "Delete Article", article_path(article), method: :delete,
                      data: { confirm: "Are your sure?"},
                      class: "btn btn-xs btn-danger  float1" %>
        </div>
      </div>
    </div>
    </div>


      <% end %>

app/views/articles/new.html.erb
<h1 align="center">Create an Article</h1>

<%= render "form" %>

app/views/articles/show.html.erb
<h2 align="center"><%= @article.title %> </h2>

<div class="well col-xs-8 col-xs-offset-2">
  <h4 class="center"></h4>
  <hr>
    <%= simple_format(@article.description.html_safe) %>

  <div class="article-actions">
    <%= link_to "View Articles", articles_path, class: "btn btn-xs btn-primary" %>

    <%= link_to "Edit Article", edit_article_path(@article), class: "btn btn-xs btn-success" %>

    <%= link_to "Delete Article", article_path(@article), method: :delete,
                data: { confirm: "Are your sure?"},
                class: "btn btn-xs btn-danger" %>
  </div>
</div>

app/views/layouts/_footers.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright &copy; Making My Own Sunshine by Nick Pounders
    </small>

  </footer>

</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
        <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a> <%# This allows you to close the message out %>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        </div>

  <% end%>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<!-- This is the page for the top menu on each page -->
<!-- Using Bootstrap for layout -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container text-center">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <!--<a class="navbar-brand" id= "logo" href="">MAKING MY OWN SUNSHINE<span style="padding-left:10px; font-size: 10px ">My Personal Blog</span></a>-->
      <%=  link_to "MAKING MY OWN SUNSHINE", root_path, class: "navbar-brand" , id: "logo"%> <p class="navbar-brand" style="padding-left:10px;font-size: 10px">My Personal Blog</p>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav">
        <!--<li><a href="#">Home <span class="sr-only">(current)</span></a></li>-->
        <li><%= link_to "Home", root_path, class: "nav navbar-nav" %></li>
        <li><%= link_to "About", about_path, class: "nav navbar-nav" %></li>
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Pages</a>
        <ul class="dropdown-menu">
          <li><%= link_to("Articles",articles_path) %></li>
          <li><%= link_to "New Article", new_article_path %></li>
          <li><a href="#">Something else here</a></li>
          <li role="separator" class="divider"></li>
          <li><a href="#">Separated link</a></li>
        </ul>
      </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Shop</a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>

        <li><%= link_to "Contact", contact_path, class: "nav navbar-nav" %></li>
        <li><%= link_to "Sign Up", contact_path, class: "nav navbar-nav" %></li>
        <li><%= link_to "Login", contact_path, class: "nav navbar-nav" %></li>
        <li><a href=""><i style="color: blue" class="fa fa-facebook-f"></i></a></li>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!-- This page will be on every page.  A good place to put nav bar but we want to keep this page clean so render
 the bar-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
  <head>
    <title>Making My Own Sunshine</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>



  </head>

  <body style="padding-top: 65px;">
    <%= render 'layouts/navigation' %> <!-- This is the navigation bar -->
    <%= render 'layouts/messages' %>

    <div class="container"> <!-- This container class creates a small amount of padding on left and right -->
      <%= yield %>
    </div>

    <%= render 'layouts/footers' %>

  </body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron">
  <div>

    <!-- This is rotating slide show with two images using Bootstrap-->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>

      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner">
        <div class="item active">
          <%= image_tag ("road_to_death_valley-wallpaper-1920x1200.jpg") %>
          <h1 class="text_over_image" style="color:white">Welcome to my Blog</h1>
        </div>

        <div class="item">
          <%= image_tag ("Girl taking pictures.jpg") %>
          <h1 class="text_over_image" style="color:white">Browse My Photo Collection</h1>
        </div>

      </div>

      <!-- Left and right controls -->
      <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="panel panel-danger">
          <div class="panel-heading">
            <h2 class="panel-title">
              <%= pluralize(obj.errors.count, "error") %>
              prohibited this article from being saved:
            </h2>
            <div class="panel-body">
              <ul>
                <% obj.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>

<% end %>